/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.anarchyco.titanium.tts;

import java.util.Locale;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import android.speech.tts.TextToSpeech;

@Kroll.module(name="Tts", id="com.anarchyco.titanium.tts")
public class TtsModule extends KrollModule implements TextToSpeech.OnInitListener
{
	private static final String LCAT = "TtsModule";
	private static final boolean DBG = TiConfig.LOGD;
	
	private boolean initialized = false;
	private TextToSpeech tts;
	
	public TtsModule(TiContext tiContext) {
		super(tiContext);
		
		tts = new TextToSpeech(tiContext.getAndroidContext(), this);
	}

	@Kroll.method
	public void speak(String text) {
		Log.d(LCAT, "speak " + text);
		
		tts.speak(text, TextToSpeech.QUEUE_FLUSH, null);
	}

	@Override
	public void onInit(int status) {
		Log.d(LCAT, "onInit " + status);
		
		initialized = true;
		tts.setLanguage(Locale.ENGLISH);
	}
}